### ISSUE TITLE
Django not getting post data

### ISSUE THREAD

**Issue by lijoev** [vsoch/django-nginx-upload#5]
I have done everything as per the documentation
All the services are up now. But when i tried uploading a file it throws me the below error. 
![error](https://user-images.githubusercontent.com/19813885/68587266-ace81b80-04ac-11ea-9545-f7ebc011c872.png)

**Comment by vsoch** [comment]
And the logs for uwsgi and Nginx? I suspect you have some permissions error so the file doesn’t upload (hence the None)

**Comment by lijoev** [comment]
No logs have been written in nginx

**Comment by vsoch** [comment]
Were you going to share uwsgi?

The fact that nginx is silent is concerning in itself - you should see every GET or POST request in those logs, including the one from the failed screen shot above. I suspect you are using some non-traditional setup (windows?) or that your containers aren't interacting as expected. The way I would debug this is to first figure out why nginx isn't showing logs, ensure that the containers are connected (e.g., that the uwsgi application going to the index page shows up in nginx logs) and then adding print statements to various parts of the application to debug. But I suspect the issue comes much earlier than that, with your original setup to begin with.

**Comment by lijoev** [comment]
[nginx.txt](https://github.com/vsoch/django-nginx-upload/files/3834559/nginx.txt)

**Below is my uwsgi config file content**
[uwsgi]
master = true
processes = 1
threads = 1
socket = :3031
chdir = /code/
post-buffering = true
log-date = true
max-requests = 5000
wsgi-file = upload/wsgi.py

**Below is my uwsgi_params file content**
uwsgi_param  QUERY_STRING       $query_string;
uwsgi_param  REQUEST_METHOD     $request_method;
uwsgi_param  CONTENT_TYPE       $content_type;
uwsgi_param  CONTENT_LENGTH     $content_length;

uwsgi_param  REQUEST_URI        $request_uri;
uwsgi_param  PATH_INFO          $document_uri;
uwsgi_param  DOCUMENT_ROOT      $document_root;
uwsgi_param  SERVER_PROTOCOL    $server_protocol;
uwsgi_param  HTTPS              $https if_not_empty;

uwsgi_param  REMOTE_ADDR        $remote_addr;
uwsgi_param  REMOTE_PORT        $remote_port;
uwsgi_param  SERVER_PORT        $server_port;
uwsgi_param  SERVER_NAME        $server_name;`

**Comment by vsoch** [comment]
Sorry I can be more clear. In your docker compose, there are three containers defined:
 
 - postgres (db)
 - nginx (web server)
 - uwsgi (the application)

what you've shown me are the nginx config and uwsgi configuration files, both of which I already have since they are provided in the repository. First - are you using the nginx container provided or are you trying to deploy this on a local or other nginx server? Second, to see logs for a container, you need to do:

```bash
docker-compose logs uwsgi
docker-compose logs nginx
docker-compose logs db
```

So far you haven't shown me anything in the way of uwsgi logs so I can't easily debug. But what we do see is that your nginx setup isn't actually working because there are no logs, period. You also haven't provided me the operating system that you are using, which could be an issue too.

I have Ubuntu 18.04, and I just cloned the repository, built the images from scratch, and everything is working as expected:

```bash
git clone https://github.com/vsoch/django-nginx-upload
$ docker-compose --version
docker-compose version 1.23.1, build b02f1306

docker-compose up -d
```
When I first start the containers, I can do
```bash
docker-compose logs nginx
```
and there is nothing there. However when I go to http://127.0,0,1 and see the interface, this obviously relies on nginx and I see content in the logs:

```
$ docker-compose logs nginx
Attaching to django-nginx-upload_nginx_1_6e837ed0ce86
nginx_1_6e837ed0ce86 | 172.17.0.1 - - [12/Nov/2019:14:35:04 +0000] "GET / HTTP/1.1" 200 1842 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36" "-"
nginx_1_6e837ed0ce86 | 172.17.0.1 - - [12/Nov/2019:14:35:04 +0000] "GET /static/js/selector.js HTTP/1.1" 200 912 "http://127.0.0.1/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36" "-"
nginx_1_6e837ed0ce86 | 172.17.0.1 - - [12/Nov/2019:14:35:09 +0000] "GET / HTTP/1.1" 200 1842 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36" "-"
nginx_1_6e837ed0ce86 | 172.17.0.1 - - [12/Nov/2019:14:35:09 +0000] "GET /static/css/style.css HTTP/1.1" 200 6014 "http://127.0.0.1/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36" "-"
nginx_1_6e837ed0ce86 | 172.17.0.1 - - [12/Nov/2019:14:35:09 +0000] "GET /static/js/selector.js HTTP/1.1" 200 912 "http://127.0.0.1/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36" "-"
```
and the interface

![image](https://user-images.githubusercontent.com/814322/68680576-e44bdc00-052f-11ea-8f30-91dd1d77ea42.png)

so if you are seeing that interface but NOT seeing anything in the logs, there is your first issue that you need to figure out. You'd also see equivalent requests in the uwsgi logs

```bash
uwsgi_1_bb735ffc91a9 | [pid: 19|app: 0|req: 1/1] 172.17.0.1 () {48 vars in 2205 bytes} [Tue Nov 12 14:35:04 2019] GET / => generated 1842 bytes in 35 msecs (HTTP/1.1 200) 5 headers in 292 bytes (1 switches on core 0)
uwsgi_1_bb735ffc91a9 | [pid: 19|app: 0|req: 2/2] 172.17.0.1 () {52 vars in 2258 bytes} [Tue Nov 12 14:35:09 2019] GET / => generated 1842 bytes in 3 msecs (HTTP/1.1 200) 5 headers in 292 bytes (1 switches on core 0)
```
And then I did hit a bug - the shared volume between the images doesn't seem to have the required folders, and permissions are off, which isn't logical because both containers make the folders, so what we need to do is create the folders locally and then bind instead (I have updated the instructions for this) -> https://github.com/vsoch/django-nginx-upload#usage

and then you can restart the containers

```
docker-compose restart
```

and the upload works!

![image](https://user-images.githubusercontent.com/814322/68681472-77394600-0531-11ea-914a-3f424d696283.png)

I'll write this here for future folks to find - when you get a 503 error it's usually that Django is having issues writing the files to the server, typically this is a permissions or (folder doesn't exist) issue. 

I've walked through a complete start to finish run and demonstrated working of the server, if you are trying to use a different nginx, or are on a non linux system it's out of scope of what I can help with.

**Comment by vsoch** [comment]
This issue was resolved, closing.
